# Generated by Django 5.2.5 on 2025-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='main.category', verbose_name='Категории'),
        ),
    ]
